// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cart.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteCartItem = `-- name: DeleteCartItem :exec
DELETE FROM cart_items
WHERE id = $1 AND user_id = $2
`

type DeleteCartItemParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"userId"`
}

func (q *Queries) DeleteCartItem(ctx context.Context, arg DeleteCartItemParams) error {
	_, err := q.db.Exec(ctx, deleteCartItem, arg.ID, arg.UserID)
	return err
}

const deleteCartItemsByUserID = `-- name: DeleteCartItemsByUserID :exec
DELETE FROM cart_items
WHERE user_id = $1
`

func (q *Queries) DeleteCartItemsByUserID(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, deleteCartItemsByUserID, userID)
	return err
}

const getCartByID = `-- name: GetCartByID :one
SELECT id, user_id, product_id, quantity, created_at, updated_at
FROM cart_items
WHERE id = $1 AND user_id = $2
`

type GetCartByIDParams struct {
	ID     int64 `json:"id"`
	UserID int64 `json:"userId"`
}

func (q *Queries) GetCartByID(ctx context.Context, arg GetCartByIDParams) (CartItem, error) {
	row := q.db.QueryRow(ctx, getCartByID, arg.ID, arg.UserID)
	var i CartItem
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProductID,
		&i.Quantity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCartItemByUserIDAndProductID = `-- name: GetCartItemByUserIDAndProductID :one
SELECT id, user_id, product_id, quantity, created_at, updated_at
FROM cart_items
WHERE user_id = $1 AND product_id = $2
`

type GetCartItemByUserIDAndProductIDParams struct {
	UserID    int64 `json:"userId"`
	ProductID int64 `json:"productId"`
}

func (q *Queries) GetCartItemByUserIDAndProductID(ctx context.Context, arg GetCartItemByUserIDAndProductIDParams) (CartItem, error) {
	row := q.db.QueryRow(ctx, getCartItemByUserIDAndProductID, arg.UserID, arg.ProductID)
	var i CartItem
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProductID,
		&i.Quantity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCartItemsByUserID = `-- name: GetCartItemsByUserID :many
SELECT ci.id, ci.user_id, ci.product_id, ci.quantity, ci.created_at, ci.updated_at,
       p.title, p.price, p.stock, p.status,
       s.name AS store_name, s.id AS store_id,
       (
           SELECT COALESCE(pi.url, '') FROM product_images pi
           WHERE pi.product_id = ci.product_id
           ORDER BY pi.position ASC LIMIT 1
       ) AS preview_image_url
FROM cart_items ci
JOIN products p ON p.id = ci.product_id
JOIN stores s ON s.id = p.store_id
WHERE ci.user_id = $1
ORDER BY ci.created_at ASC
`

type GetCartItemsByUserIDRow struct {
	ID              int64              `json:"id"`
	UserID          int64              `json:"userId"`
	ProductID       int64              `json:"productId"`
	Quantity        int32              `json:"quantity"`
	CreatedAt       pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt       pgtype.Timestamptz `json:"updatedAt"`
	Title           string             `json:"title"`
	Price           pgtype.Numeric     `json:"price"`
	Stock           int32              `json:"stock"`
	Status          ProductStatus      `json:"status"`
	StoreName       string             `json:"storeName"`
	StoreID         int64              `json:"storeId"`
	PreviewImageUrl string             `json:"previewImageUrl"`
}

func (q *Queries) GetCartItemsByUserID(ctx context.Context, userID int64) ([]GetCartItemsByUserIDRow, error) {
	rows, err := q.db.Query(ctx, getCartItemsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCartItemsByUserIDRow
	for rows.Next() {
		var i GetCartItemsByUserIDRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProductID,
			&i.Quantity,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Title,
			&i.Price,
			&i.Stock,
			&i.Status,
			&i.StoreName,
			&i.StoreID,
			&i.PreviewImageUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCartItemQuantity = `-- name: UpdateCartItemQuantity :one
UPDATE cart_items
SET quantity = $3, updated_at = now()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, product_id, quantity, created_at, updated_at
`

type UpdateCartItemQuantityParams struct {
	ID       int64 `json:"id"`
	UserID   int64 `json:"userId"`
	Quantity int32 `json:"quantity"`
}

func (q *Queries) UpdateCartItemQuantity(ctx context.Context, arg UpdateCartItemQuantityParams) (CartItem, error) {
	row := q.db.QueryRow(ctx, updateCartItemQuantity, arg.ID, arg.UserID, arg.Quantity)
	var i CartItem
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProductID,
		&i.Quantity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertCartItem = `-- name: UpsertCartItem :one

INSERT INTO cart_items (user_id, product_id, quantity)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, product_id)
DO UPDATE SET quantity = EXCLUDED.quantity, updated_at = now()
RETURNING id, user_id, product_id, quantity, created_at, updated_at
`

type UpsertCartItemParams struct {
	UserID    int64 `json:"userId"`
	ProductID int64 `json:"productId"`
	Quantity  int32 `json:"quantity"`
}

// cart_items
func (q *Queries) UpsertCartItem(ctx context.Context, arg UpsertCartItemParams) (CartItem, error) {
	row := q.db.QueryRow(ctx, upsertCartItem, arg.UserID, arg.ProductID, arg.Quantity)
	var i CartItem
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProductID,
		&i.Quantity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
