// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: orders.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countOrderItems = `-- name: CountOrderItems :one
SELECT COUNT(*) FROM order_items WHERE order_id = $1
`

func (q *Queries) CountOrderItems(ctx context.Context, orderID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countOrderItems, orderID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (user_id, status, total, address)
VALUES ($1, 'pending', $2, $3)
RETURNING id, user_id, status, total, address, created_at, updated_at
`

type CreateOrderParams struct {
	UserID  int64          `json:"userId"`
	Total   pgtype.Numeric `json:"total"`
	Address string         `json:"address"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder, arg.UserID, arg.Total, arg.Address)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.Total,
		&i.Address,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createOrderItem = `-- name: CreateOrderItem :one
INSERT INTO order_items (order_id, product_id, quantity, price)
VALUES ($1, $2, $3, $4)
RETURNING id, order_id, product_id, quantity, price
`

type CreateOrderItemParams struct {
	OrderID   int64          `json:"orderId"`
	ProductID int64          `json:"productId"`
	Quantity  int32          `json:"quantity"`
	Price     pgtype.Numeric `json:"price"`
}

func (q *Queries) CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error) {
	row := q.db.QueryRow(ctx, createOrderItem,
		arg.OrderID,
		arg.ProductID,
		arg.Quantity,
		arg.Price,
	)
	var i OrderItem
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.ProductID,
		&i.Quantity,
		&i.Price,
	)
	return i, err
}

const decrementProductStock = `-- name: DecrementProductStock :one
UPDATE products
SET stock = stock - $2
WHERE id = $1 AND stock >= $2
RETURNING id, store_id, title, price, stock
`

type DecrementProductStockParams struct {
	ID    int64 `json:"id"`
	Stock int32 `json:"stock"`
}

type DecrementProductStockRow struct {
	ID      int64          `json:"id"`
	StoreID int64          `json:"storeId"`
	Title   string         `json:"title"`
	Price   pgtype.Numeric `json:"price"`
	Stock   int32          `json:"stock"`
}

func (q *Queries) DecrementProductStock(ctx context.Context, arg DecrementProductStockParams) (DecrementProductStockRow, error) {
	row := q.db.QueryRow(ctx, decrementProductStock, arg.ID, arg.Stock)
	var i DecrementProductStockRow
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.Title,
		&i.Price,
		&i.Stock,
	)
	return i, err
}

const getOrder = `-- name: GetOrder :one
SELECT o.id, o.user_id, o.status, o.total, o.address, o.created_at, o.updated_at
FROM orders o
WHERE o.id = $1
`

func (q *Queries) GetOrder(ctx context.Context, id int64) (Order, error) {
	row := q.db.QueryRow(ctx, getOrder, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.Total,
		&i.Address,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrderItems = `-- name: GetOrderItems :many
SELECT oi.id, oi.order_id, oi.product_id, oi.quantity, oi.price,
       p.title AS product_title, p.store_id
FROM order_items oi
JOIN products p ON p.id = oi.product_id
WHERE oi.order_id = $1
`

type GetOrderItemsRow struct {
	ID           int64          `json:"id"`
	OrderID      int64          `json:"orderId"`
	ProductID    int64          `json:"productId"`
	Quantity     int32          `json:"quantity"`
	Price        pgtype.Numeric `json:"price"`
	ProductTitle string         `json:"productTitle"`
	StoreID      int64          `json:"storeId"`
}

func (q *Queries) GetOrderItems(ctx context.Context, orderID int64) ([]GetOrderItemsRow, error) {
	rows, err := q.db.Query(ctx, getOrderItems, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetOrderItemsRow
	for rows.Next() {
		var i GetOrderItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.ProductID,
			&i.Quantity,
			&i.Price,
			&i.ProductTitle,
			&i.StoreID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrderItemsByOrderID = `-- name: GetOrderItemsByOrderID :many
SELECT product_id, quantity FROM order_items WHERE order_id = $1
`

type GetOrderItemsByOrderIDRow struct {
	ProductID int64 `json:"productId"`
	Quantity  int32 `json:"quantity"`
}

func (q *Queries) GetOrderItemsByOrderID(ctx context.Context, orderID int64) ([]GetOrderItemsByOrderIDRow, error) {
	rows, err := q.db.Query(ctx, getOrderItemsByOrderID, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetOrderItemsByOrderIDRow
	for rows.Next() {
		var i GetOrderItemsByOrderIDRow
		if err := rows.Scan(&i.ProductID, &i.Quantity); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrderWithItems = `-- name: GetOrderWithItems :one
SELECT o.id, o.user_id, o.status, o.total, o.address, o.created_at, o.updated_at,
       oi.id AS item_id, oi.product_id, oi.quantity, oi.price,
       p.title AS product_title, p.store_id
FROM orders o
JOIN order_items oi ON oi.order_id = o.id
JOIN products p ON p.id = oi.product_id
WHERE o.id = $1
`

type GetOrderWithItemsRow struct {
	ID           int64              `json:"id"`
	UserID       int64              `json:"userId"`
	Status       OrderStatus        `json:"status"`
	Total        pgtype.Numeric     `json:"total"`
	Address      string             `json:"address"`
	CreatedAt    pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt    pgtype.Timestamptz `json:"updatedAt"`
	ItemID       int64              `json:"itemId"`
	ProductID    int64              `json:"productId"`
	Quantity     int32              `json:"quantity"`
	Price        pgtype.Numeric     `json:"price"`
	ProductTitle string             `json:"productTitle"`
	StoreID      int64              `json:"storeId"`
}

func (q *Queries) GetOrderWithItems(ctx context.Context, id int64) (GetOrderWithItemsRow, error) {
	row := q.db.QueryRow(ctx, getOrderWithItems, id)
	var i GetOrderWithItemsRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.Total,
		&i.Address,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ItemID,
		&i.ProductID,
		&i.Quantity,
		&i.Price,
		&i.ProductTitle,
		&i.StoreID,
	)
	return i, err
}

const getProductStoreID = `-- name: GetProductStoreID :one
SELECT store_id FROM products WHERE id = $1
`

func (q *Queries) GetProductStoreID(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRow(ctx, getProductStoreID, id)
	var store_id int64
	err := row.Scan(&store_id)
	return store_id, err
}

const incrementProductStock = `-- name: IncrementProductStock :one
UPDATE products
SET stock = stock + $2
WHERE id = $1
RETURNING id, store_id, title, price, stock
`

type IncrementProductStockParams struct {
	ID    int64 `json:"id"`
	Stock int32 `json:"stock"`
}

type IncrementProductStockRow struct {
	ID      int64          `json:"id"`
	StoreID int64          `json:"storeId"`
	Title   string         `json:"title"`
	Price   pgtype.Numeric `json:"price"`
	Stock   int32          `json:"stock"`
}

func (q *Queries) IncrementProductStock(ctx context.Context, arg IncrementProductStockParams) (IncrementProductStockRow, error) {
	row := q.db.QueryRow(ctx, incrementProductStock, arg.ID, arg.Stock)
	var i IncrementProductStockRow
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.Title,
		&i.Price,
		&i.Stock,
	)
	return i, err
}

const listOrdersBySeller = `-- name: ListOrdersBySeller :many
SELECT DISTINCT o.id, o.user_id, o.status, o.total, o.address, o.created_at, o.updated_at
FROM orders o
JOIN order_items oi ON oi.order_id = o.id
JOIN products p ON p.id = oi.product_id
JOIN stores s ON s.id = p.store_id
WHERE s.user_id = $1
ORDER BY o.created_at DESC
LIMIT $2 OFFSET $3
`

type ListOrdersBySellerParams struct {
	UserID int64 `json:"userId"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListOrdersBySeller(ctx context.Context, arg ListOrdersBySellerParams) ([]Order, error) {
	rows, err := q.db.Query(ctx, listOrdersBySeller, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Status,
			&i.Total,
			&i.Address,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrdersBySellerCount = `-- name: ListOrdersBySellerCount :one
SELECT COUNT(DISTINCT o.id)
FROM orders o
JOIN order_items oi ON oi.order_id = o.id
JOIN products p ON p.id = oi.product_id
JOIN stores s ON s.id = p.store_id
WHERE s.user_id = $1
`

func (q *Queries) ListOrdersBySellerCount(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, listOrdersBySellerCount, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listOrdersByUser = `-- name: ListOrdersByUser :many
SELECT o.id, o.user_id, o.status, o.total, o.address, o.created_at, o.updated_at
FROM orders o
WHERE o.user_id = $1
ORDER BY o.created_at DESC
LIMIT $2 OFFSET $3
`

type ListOrdersByUserParams struct {
	UserID int64 `json:"userId"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListOrdersByUser(ctx context.Context, arg ListOrdersByUserParams) ([]Order, error) {
	rows, err := q.db.Query(ctx, listOrdersByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Status,
			&i.Total,
			&i.Address,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrdersByUserCount = `-- name: ListOrdersByUserCount :one
SELECT COUNT(*)
FROM orders o
WHERE o.user_id = $1
`

func (q *Queries) ListOrdersByUserCount(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, listOrdersByUserCount, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const updateOrderStatus = `-- name: UpdateOrderStatus :one
UPDATE orders
SET status = $2,
    updated_at = now()
WHERE id = $1
RETURNING id, user_id, status, total, address, created_at, updated_at
`

type UpdateOrderStatusParams struct {
	ID     int64       `json:"id"`
	Status OrderStatus `json:"status"`
}

func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (Order, error) {
	row := q.db.QueryRow(ctx, updateOrderStatus, arg.ID, arg.Status)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Status,
		&i.Total,
		&i.Address,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
