// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payments.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPayment = `-- name: CreatePayment :one
INSERT INTO payments (order_id, amount, currency, status, provider, provider_payment_id)
VALUES ($1, $2, $3, 'pending', $4, $5)
RETURNING id, order_id, amount, currency, status, provider, provider_payment_id, created_at, updated_at
`

type CreatePaymentParams struct {
	OrderID           int64          `json:"orderId"`
	Amount            pgtype.Numeric `json:"amount"`
	Currency          string         `json:"currency"`
	Provider          string         `json:"provider"`
	ProviderPaymentID pgtype.Text    `json:"providerPaymentId"`
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, createPayment,
		arg.OrderID,
		arg.Amount,
		arg.Currency,
		arg.Provider,
		arg.ProviderPaymentID,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.Provider,
		&i.ProviderPaymentID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPayment = `-- name: GetPayment :one
SELECT id, order_id, amount, currency, status, provider, provider_payment_id, created_at, updated_at
FROM payments
WHERE id = $1
`

func (q *Queries) GetPayment(ctx context.Context, id int64) (Payment, error) {
	row := q.db.QueryRow(ctx, getPayment, id)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.Provider,
		&i.ProviderPaymentID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentByOrderID = `-- name: GetPaymentByOrderID :one
SELECT id, order_id, amount, currency, status, provider, provider_payment_id, created_at, updated_at
FROM payments
WHERE order_id = $1
`

func (q *Queries) GetPaymentByOrderID(ctx context.Context, orderID int64) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentByOrderID, orderID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.Provider,
		&i.ProviderPaymentID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePaymentStatus = `-- name: UpdatePaymentStatus :one
UPDATE payments
SET status = $2,
    provider_payment_id = COALESCE($3, provider_payment_id),
    updated_at = now()
WHERE id = $1
RETURNING id, order_id, amount, currency, status, provider, provider_payment_id, created_at, updated_at
`

type UpdatePaymentStatusParams struct {
	ID                int64         `json:"id"`
	Status            PaymentStatus `json:"status"`
	ProviderPaymentID pgtype.Text   `json:"providerPaymentId"`
}

func (q *Queries) UpdatePaymentStatus(ctx context.Context, arg UpdatePaymentStatusParams) (Payment, error) {
	row := q.db.QueryRow(ctx, updatePaymentStatus, arg.ID, arg.Status, arg.ProviderPaymentID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.Provider,
		&i.ProviderPaymentID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
