// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payments.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPayment = `-- name: CreatePayment :one
INSERT INTO payments (order_id, amount, currency, status, provider, provider_payment_id)
VALUES ($1, $2, $3, 'pending', $4, $5)
RETURNING id, order_id, amount, currency, status, provider, provider_payment_id, created_at, updated_at
`

type CreatePaymentParams struct {
	OrderID           int64          `json:"orderId"`
	Amount            pgtype.Numeric `json:"amount"`
	Currency          string         `json:"currency"`
	Provider          string         `json:"provider"`
	ProviderPaymentID pgtype.Text    `json:"providerPaymentId"`
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, createPayment,
		arg.OrderID,
		arg.Amount,
		arg.Currency,
		arg.Provider,
		arg.ProviderPaymentID,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.Provider,
		&i.ProviderPaymentID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPayment = `-- name: GetPayment :one
SELECT id, order_id, amount, currency, status, provider, provider_payment_id, created_at, updated_at FROM payments WHERE id = $1
`

func (q *Queries) GetPayment(ctx context.Context, id int64) (Payment, error) {
	row := q.db.QueryRow(ctx, getPayment, id)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.Provider,
		&i.ProviderPaymentID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentByOrderID = `-- name: GetPaymentByOrderID :one
SELECT id, order_id, amount, currency, status, provider, provider_payment_id, created_at, updated_at FROM payments WHERE order_id = $1
`

func (q *Queries) GetPaymentByOrderID(ctx context.Context, orderID int64) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentByOrderID, orderID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.Provider,
		&i.ProviderPaymentID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPaymentsByUserID = `-- name: ListPaymentsByUserID :many
SELECT p.id, p.order_id, p.amount, p.currency, p.status, p.provider, p.provider_payment_id, p.created_at, p.updated_at
FROM payments p
JOIN orders o ON o.id = p.order_id
WHERE o.user_id = $1::bigint
ORDER BY p.created_at DESC
LIMIT $2 OFFSET $3
`

type ListPaymentsByUserIDParams struct {
	Column1 int64 `json:"column1"`
	Limit   int32 `json:"limit"`
	Offset  int32 `json:"offset"`
}

func (q *Queries) ListPaymentsByUserID(ctx context.Context, arg ListPaymentsByUserIDParams) ([]Payment, error) {
	rows, err := q.db.Query(ctx, listPaymentsByUserID, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Payment
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.Amount,
			&i.Currency,
			&i.Status,
			&i.Provider,
			&i.ProviderPaymentID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPaymentsByUserIDCount = `-- name: ListPaymentsByUserIDCount :one
SELECT COUNT(*)
FROM payments p
JOIN orders o ON o.id = p.order_id
WHERE o.user_id = $1::bigint
`

func (q *Queries) ListPaymentsByUserIDCount(ctx context.Context, dollar_1 int64) (int64, error) {
	row := q.db.QueryRow(ctx, listPaymentsByUserIDCount, dollar_1)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const updatePaymentStatus = `-- name: UpdatePaymentStatus :one
UPDATE payments
SET status = $2,
    provider_payment_id = COALESCE($3, provider_payment_id),
    updated_at = now()
WHERE id = $1
RETURNING id, order_id, amount, currency, status, provider, provider_payment_id, created_at, updated_at
`

type UpdatePaymentStatusParams struct {
	ID                int64         `json:"id"`
	Status            PaymentStatus `json:"status"`
	ProviderPaymentID pgtype.Text   `json:"providerPaymentId"`
}

func (q *Queries) UpdatePaymentStatus(ctx context.Context, arg UpdatePaymentStatusParams) (Payment, error) {
	row := q.db.QueryRow(ctx, updatePaymentStatus, arg.ID, arg.Status, arg.ProviderPaymentID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.Amount,
		&i.Currency,
		&i.Status,
		&i.Provider,
		&i.ProviderPaymentID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
