// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: products.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgtype"
)

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (store_id, category_id, title, description, price, stock, status)
VALUES ($1, $2, $3, $4, $5, $6, 'pending')
RETURNING id, store_id, category_id, title, description, price, stock, status, created_at, updated_at
`

type CreateProductParams struct {
	StoreID     int64          `json:"storeId"`
	CategoryID  pgtype.Int8    `json:"categoryId"`
	Title       string         `json:"title"`
	Description pgtype.Text    `json:"description"`
	Price       pgtype.Numeric `json:"price"`
	Stock       int32          `json:"stock"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.StoreID,
		arg.CategoryID,
		arg.Title,
		arg.Description,
		arg.Price,
		arg.Stock,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.CategoryID,
		&i.Title,
		&i.Description,
		&i.Price,
		&i.Stock,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createProductImage = `-- name: CreateProductImage :one
INSERT INTO product_images (product_id, url, position, object_key)
VALUES ($1, $2, $3, $4)
RETURNING id, product_id, url, position, object_key
`

type CreateProductImageParams struct {
	ProductID int64       `json:"productId"`
	Url       string      `json:"url"`
	Position  int32       `json:"position"`
	ObjectKey pgtype.Text `json:"objectKey"`
}

func (q *Queries) CreateProductImage(ctx context.Context, arg CreateProductImageParams) (ProductImage, error) {
	row := q.db.QueryRow(ctx, createProductImage,
		arg.ProductID,
		arg.Url,
		arg.Position,
		arg.ObjectKey,
	)
	var i ProductImage
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Url,
		&i.Position,
		&i.ObjectKey,
	)
	return i, err
}

const deleteImageByID = `-- name: DeleteImageByID :exec
DELETE FROM product_images
WHERE id = $1
`

func (q *Queries) DeleteImageByID(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteImageByID, id)
	return err
}

const deleteProduct = `-- name: DeleteProduct :exec
DELETE FROM products
WHERE id = $1
`

func (q *Queries) DeleteProduct(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteProduct, id)
	return err
}

const deleteProductImages = `-- name: DeleteProductImages :exec
DELETE FROM product_images
WHERE product_id = $1
`

func (q *Queries) DeleteProductImages(ctx context.Context, productID int64) error {
	_, err := q.db.Exec(ctx, deleteProductImages, productID)
	return err
}

const getImageByID = `-- name: GetImageByID :one
SELECT id, product_id, url, position, object_key
FROM product_images
WHERE id = $1
`

func (q *Queries) GetImageByID(ctx context.Context, id int64) (ProductImage, error) {
	row := q.db.QueryRow(ctx, getImageByID, id)
	var i ProductImage
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Url,
		&i.Position,
		&i.ObjectKey,
	)
	return i, err
}

const getProduct = `-- name: GetProduct :one
SELECT p.id, p.store_id, p.category_id, p.title, p.description,
       p.price, p.stock, p.status, p.created_at, p.updated_at,
       s.name AS store_name, s.description AS store_description,
       c.name AS category_name, c.slug AS category_slug
FROM products p
LEFT JOIN stores s ON p.store_id = s.id
LEFT JOIN categories c ON p.category_id = c.id
WHERE p.id = $1
`

type GetProductRow struct {
	ID               int64              `json:"id"`
	StoreID          int64              `json:"storeId"`
	CategoryID       pgtype.Int8        `json:"categoryId"`
	Title            string             `json:"title"`
	Description      pgtype.Text        `json:"description"`
	Price            pgtype.Numeric     `json:"price"`
	Stock            int32              `json:"stock"`
	Status           ProductStatus      `json:"status"`
	CreatedAt        pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt        pgtype.Timestamptz `json:"updatedAt"`
	StoreName        pgtype.Text        `json:"storeName"`
	StoreDescription pgtype.Text        `json:"storeDescription"`
	CategoryName     pgtype.Text        `json:"categoryName"`
	CategorySlug     pgtype.Text        `json:"categorySlug"`
}

func (q *Queries) GetProduct(ctx context.Context, id int64) (GetProductRow, error) {
	row := q.db.QueryRow(ctx, getProduct, id)
	var i GetProductRow
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.CategoryID,
		&i.Title,
		&i.Description,
		&i.Price,
		&i.Stock,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StoreName,
		&i.StoreDescription,
		&i.CategoryName,
		&i.CategorySlug,
	)
	return i, err
}

const getProductStoreOwner = `-- name: GetProductStoreOwner :one
SELECT p.id, s.user_id AS store_owner_id
FROM products p
JOIN stores s ON p.store_id = s.id
WHERE p.id = $1
`

type GetProductStoreOwnerRow struct {
	ID           int64 `json:"id"`
	StoreOwnerID int64 `json:"storeOwnerId"`
}

func (q *Queries) GetProductStoreOwner(ctx context.Context, id int64) (GetProductStoreOwnerRow, error) {
	row := q.db.QueryRow(ctx, getProductStoreOwner, id)
	var i GetProductStoreOwnerRow
	err := row.Scan(&i.ID, &i.StoreOwnerID)
	return i, err
}

const listCategories = `-- name: ListCategories :many
WITH recursive category_tree AS (
    SELECT id, parent_id, name, slug, 0 AS depth
    FROM categories
    WHERE parent_id IS NULL
    UNION ALL
    SELECT c.id, c.parent_id, c.name, c.slug, ct.depth + 1
    FROM categories c
    INNER JOIN category_tree ct ON c.parent_id = ct.id
)
SELECT id, parent_id, name, slug
FROM category_tree
ORDER BY id
`

type ListCategoriesRow struct {
	ID       int64       `json:"id"`
	ParentID pgtype.Int8 `json:"parentId"`
	Name     string      `json:"name"`
	Slug     string      `json:"slug"`
}

func (q *Queries) ListCategories(ctx context.Context) ([]ListCategoriesRow, error) {
	rows, err := q.db.Query(ctx, listCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCategoriesRow
	for rows.Next() {
		var i ListCategoriesRow
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Name,
			&i.Slug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductImages = `-- name: ListProductImages :many
SELECT id, product_id, url, position, object_key
FROM product_images
WHERE product_id = $1
ORDER BY position ASC
`

func (q *Queries) ListProductImages(ctx context.Context, productID int64) ([]ProductImage, error) {
	rows, err := q.db.Query(ctx, listProductImages, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProductImage
	for rows.Next() {
		var i ProductImage
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.Url,
			&i.Position,
			&i.ObjectKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductImagesByProductIDs = `-- name: ListProductImagesByProductIDs :many
SELECT id, product_id, url, position, object_key
FROM product_images
WHERE product_id = ANY($1::bigint[])
ORDER BY product_id, position ASC
`

func (q *Queries) ListProductImagesByProductIDs(ctx context.Context, dollar_1 []int64) ([]ProductImage, error) {
	rows, err := q.db.Query(ctx, listProductImagesByProductIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProductImage
	for rows.Next() {
		var i ProductImage
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.Url,
			&i.Position,
			&i.ObjectKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProducts = `-- name: ListProducts :many
SELECT p.id, p.store_id, p.category_id, p.title, p.description,
       p.price, p.stock, p.status, p.created_at, p.updated_at,
       s.name AS store_name, s.description AS store_description,
       c.name AS category_name, c.slug AS category_slug
FROM products p
LEFT JOIN stores s ON p.store_id = s.id
LEFT JOIN categories c ON p.category_id = c.id
WHERE ($1::bigint IS NULL OR p.store_id = $1)
  AND ($2::bigint IS NULL OR p.category_id = $2)
  AND ($3::numeric IS NULL OR p.price >= $3)
  AND ($4::numeric IS NULL OR p.price <= $4)
  AND ($5::text IS NULL OR p.title ILIKE $5)
  AND p.status = 'active'
ORDER BY
  CASE WHEN $6::text = 'price_asc' THEN p.price END ASC,
  CASE WHEN $6::text = 'price_desc' THEN p.price END DESC,
  CASE WHEN $6::text = 'created_desc' THEN p.created_at END DESC
LIMIT $8 OFFSET $7
`

type ListProductsParams struct {
	StoreID     pgtype.Int8    `json:"storeId"`
	CategoryID  pgtype.Int8    `json:"categoryId"`
	MinPrice    pgtype.Numeric `json:"minPrice"`
	MaxPrice    pgtype.Numeric `json:"maxPrice"`
	Search      pgtype.Text    `json:"search"`
	Sort        string         `json:"sort"`
	OffsetCount int32          `json:"offsetCount"`
	LimitCount  int32          `json:"limitCount"`
}

type ListProductsRow struct {
	ID               int64              `json:"id"`
	StoreID          int64              `json:"storeId"`
	CategoryID       pgtype.Int8        `json:"categoryId"`
	Title            string             `json:"title"`
	Description      pgtype.Text        `json:"description"`
	Price            pgtype.Numeric     `json:"price"`
	Stock            int32              `json:"stock"`
	Status           ProductStatus      `json:"status"`
	CreatedAt        pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt        pgtype.Timestamptz `json:"updatedAt"`
	StoreName        pgtype.Text        `json:"storeName"`
	StoreDescription pgtype.Text        `json:"storeDescription"`
	CategoryName     pgtype.Text        `json:"categoryName"`
	CategorySlug     pgtype.Text        `json:"categorySlug"`
}

func (q *Queries) ListProducts(ctx context.Context, arg ListProductsParams) ([]ListProductsRow, error) {
	rows, err := q.db.Query(ctx, listProducts,
		arg.StoreID,
		arg.CategoryID,
		arg.MinPrice,
		arg.MaxPrice,
		arg.Search,
		arg.Sort,
		arg.OffsetCount,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProductsRow
	for rows.Next() {
		var i ListProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.StoreID,
			&i.CategoryID,
			&i.Title,
			&i.Description,
			&i.Price,
			&i.Stock,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StoreName,
			&i.StoreDescription,
			&i.CategoryName,
			&i.CategorySlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductsCount = `-- name: ListProductsCount :one
SELECT COUNT(*)
FROM products p
WHERE ($1::bigint IS NULL OR p.store_id = $1)
  AND ($2::bigint IS NULL OR p.category_id = $2)
  AND ($3::numeric IS NULL OR p.price >= $3)
  AND ($4::numeric IS NULL OR p.price <= $4)
  AND ($5::text IS NULL OR p.title ILIKE $5)
  AND p.status = 'active'
`

type ListProductsCountParams struct {
	StoreID    pgtype.Int8    `json:"storeId"`
	CategoryID pgtype.Int8    `json:"categoryId"`
	MinPrice   pgtype.Numeric `json:"minPrice"`
	MaxPrice   pgtype.Numeric `json:"maxPrice"`
	Search     pgtype.Text    `json:"search"`
}

func (q *Queries) ListProductsCount(ctx context.Context, arg ListProductsCountParams) (int64, error) {
	row := q.db.QueryRow(ctx, listProductsCount,
		arg.StoreID,
		arg.CategoryID,
		arg.MinPrice,
		arg.MaxPrice,
		arg.Search,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const moderateProduct = `-- name: ModerateProduct :execresult
UPDATE products
SET status = $2,
    updated_at = now()
WHERE id = $1
`

type ModerateProductParams struct {
	ID     int64         `json:"id"`
	Status ProductStatus `json:"status"`
}

func (q *Queries) ModerateProduct(ctx context.Context, arg ModerateProductParams) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, moderateProduct, arg.ID, arg.Status)
}

const updateProduct = `-- name: UpdateProduct :one
UPDATE products
SET title       = COALESCE($1, title),
    description = COALESCE($2, description),
    price       = COALESCE($3, price),
    stock       = COALESCE($4, stock)
WHERE id = $5
RETURNING id, store_id, category_id, title, description, price, stock, status, created_at, updated_at
`

type UpdateProductParams struct {
	Title       pgtype.Text    `json:"title"`
	Description pgtype.Text    `json:"description"`
	Price       pgtype.Numeric `json:"price"`
	Stock       pgtype.Int4    `json:"stock"`
	ID          int64          `json:"id"`
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, updateProduct,
		arg.Title,
		arg.Description,
		arg.Price,
		arg.Stock,
		arg.ID,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.CategoryID,
		&i.Title,
		&i.Description,
		&i.Price,
		&i.Stock,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
