// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: seller_applications.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countPendingSellerApplications = `-- name: CountPendingSellerApplications :one
SELECT COUNT(*) FROM seller_applications WHERE status = 'pending'
`

func (q *Queries) CountPendingSellerApplications(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countPendingSellerApplications)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSellerApplication = `-- name: CreateSellerApplication :one
INSERT INTO seller_applications (user_id, store_name, description)
VALUES ($1, $2, $3)
RETURNING id, user_id, store_name, description, status, created_at, updated_at
`

type CreateSellerApplicationParams struct {
	UserID      int64       `json:"userId"`
	StoreName   string      `json:"storeName"`
	Description pgtype.Text `json:"description"`
}

func (q *Queries) CreateSellerApplication(ctx context.Context, arg CreateSellerApplicationParams) (SellerApplication, error) {
	row := q.db.QueryRow(ctx, createSellerApplication, arg.UserID, arg.StoreName, arg.Description)
	var i SellerApplication
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StoreName,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPendingSellerApplicationByUserID = `-- name: GetPendingSellerApplicationByUserID :one
SELECT id, user_id, store_name, description, status, created_at, updated_at
FROM seller_applications
WHERE user_id = $1 AND status = 'pending'
LIMIT 1
`

func (q *Queries) GetPendingSellerApplicationByUserID(ctx context.Context, userID int64) (SellerApplication, error) {
	row := q.db.QueryRow(ctx, getPendingSellerApplicationByUserID, userID)
	var i SellerApplication
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StoreName,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSellerApplicationByID = `-- name: GetSellerApplicationByID :one
SELECT id, user_id, store_name, description, status, created_at, updated_at
FROM seller_applications
WHERE id = $1
`

func (q *Queries) GetSellerApplicationByID(ctx context.Context, id int64) (SellerApplication, error) {
	row := q.db.QueryRow(ctx, getSellerApplicationByID, id)
	var i SellerApplication
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StoreName,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPendingSellerApplications = `-- name: ListPendingSellerApplications :many
SELECT id, user_id, store_name, description, status, created_at, updated_at
FROM seller_applications
WHERE status = 'pending'
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListPendingSellerApplicationsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListPendingSellerApplications(ctx context.Context, arg ListPendingSellerApplicationsParams) ([]SellerApplication, error) {
	rows, err := q.db.Query(ctx, listPendingSellerApplications, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SellerApplication
	for rows.Next() {
		var i SellerApplication
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.StoreName,
			&i.Description,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSellerApplicationsByUser = `-- name: ListSellerApplicationsByUser :many
SELECT id, user_id, store_name, description, status, created_at, updated_at
FROM seller_applications
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListSellerApplicationsByUser(ctx context.Context, userID int64) ([]SellerApplication, error) {
	rows, err := q.db.Query(ctx, listSellerApplicationsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SellerApplication
	for rows.Next() {
		var i SellerApplication
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.StoreName,
			&i.Description,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSellerApplicationStatus = `-- name: UpdateSellerApplicationStatus :one
UPDATE seller_applications
SET status = $2,
    updated_at = now()
WHERE id = $1
RETURNING id, user_id, store_name, description, status, created_at, updated_at
`

type UpdateSellerApplicationStatusParams struct {
	ID     int64  `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) UpdateSellerApplicationStatus(ctx context.Context, arg UpdateSellerApplicationStatusParams) (SellerApplication, error) {
	row := q.db.QueryRow(ctx, updateSellerApplicationStatus, arg.ID, arg.Status)
	var i SellerApplication
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.StoreName,
		&i.Description,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
