// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createStore = `-- name: CreateStore :one
INSERT INTO stores (user_id, name, description, logo_url)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, name, description, logo_url, created_at, updated_at
`

type CreateStoreParams struct {
	UserID      int64       `json:"userId"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	LogoUrl     pgtype.Text `json:"logoUrl"`
}

func (q *Queries) CreateStore(ctx context.Context, arg CreateStoreParams) (Store, error) {
	row := q.db.QueryRow(ctx, createStore,
		arg.UserID,
		arg.Name,
		arg.Description,
		arg.LogoUrl,
	)
	var i Store
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.LogoUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getStoreByUserID = `-- name: GetStoreByUserID :one
SELECT id, user_id, name, description, logo_url, created_at, updated_at
FROM stores
WHERE user_id = $1
`

func (q *Queries) GetStoreByUserID(ctx context.Context, userID int64) (Store, error) {
	row := q.db.QueryRow(ctx, getStoreByUserID, userID)
	var i Store
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.LogoUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getStoreOwnerByStoreID = `-- name: GetStoreOwnerByStoreID :one
SELECT s.user_id
FROM stores s
WHERE s.id = $1
`

func (q *Queries) GetStoreOwnerByStoreID(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRow(ctx, getStoreOwnerByStoreID, id)
	var user_id int64
	err := row.Scan(&user_id)
	return user_id, err
}

const updateUserRole = `-- name: UpdateUserRole :one
UPDATE users
SET role = $2
WHERE id = $1
RETURNING id, email, password_hash, role, username, avatar_url, phone, created_at, updated_at
`

type UpdateUserRoleParams struct {
	ID   int64    `json:"id"`
	Role UserRole `json:"role"`
}

func (q *Queries) UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserRole, arg.ID, arg.Role)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.Username,
		&i.AvatarUrl,
		&i.Phone,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
